<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Perl/codepiece/try-catch-exception01 - Glamenv-Septzen(ぐらめぬ・ぜぷつぇん)(archive)</title>
<!-- favicon 2017's reference:
https://developers.google.com/web/fundamentals/design-and-ui/browser-customization/
https://msdn.microsoft.com/ja-jp/library/dn455106(v=vs.85).aspx
https://developer.chrome.com/multidevice/android/installtohomescreen
https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html
-->
<link rel="shortcut icon" href="../favicons/favicon.ico" type="image/vnd.microsoft.icon">
<link rel="icon" href="../favicons/favicon.ico" type="image/vnd.microsoft.icon">
<link rel="apple-touch-icon" sizes="57x57" href="../favicons/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="../favicons/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="../favicons/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="../favicons/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="../favicons/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="../favicons/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="../favicons/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="../favicons/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="../favicons/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="../favicons/android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="../favicons/favicon-48x48.png" sizes="48x48">
<link rel="icon" type="image/png" href="../favicons/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="../favicons/favicon-160x160.png" sizes="96x96">
<link rel="icon" type="image/png" href="../favicons/favicon-196x196.png" sizes="96x96">
<link rel="icon" type="image/png" href="../favicons/favicon-16x16.png" sizes="16x16">
<link rel="icon" type="image/png" href="../favicons/favicon-32x32.png" sizes="32x32">

<!-- browserconfig.xml : https://msdn.microsoft.com/ja-jp/library/dn455106(v=vs.85).aspx -->
<meta name="msapplication-TileColor" content="#990000">
<meta name="msapplication-TileImage" content="../favicons/mstile-144x144.png">

<!-- these favicon files were generated by https://ao-system.net/favicongenerator/ , thanks!!(2017-02-18) -->

<style type="text/css"></style>

<link href="./css/pcbrowser.css" rel="stylesheet" type="text/css" media="screen"/>
<link href="./css/pcbrowser_plugins.css" rel="stylesheet" type="text/css" media="screen"/>
<link href="./css/pcbrowser_wiki.css" rel="stylesheet" type="text/css" media="screen"/>
<link href="./css/print.css" rel="stylesheet" type="text/css" media="print"/>
</head>
<body>
<!-- body start -->
<div class="body">
<div style="display: inline"><a name="pagetop"></a></div>
<div id="header-wrap">
<img src="./images/logo1.jpg" style="float: left; margin-right: 1em;"/>
<a href="./index.html" title="Glamenv-Septzen(ぐらめぬ・ぜぷつぇん)(archive)"><img src="./icons/home.png" alt="home"/>&nbsp;Glamenv-Septzen(ぐらめぬ・ぜぷつぇん)(archive)</a>


<h1 style="margin-bottom: 10px;">Perl/codepiece/try-catch-exception01</h1>

<div style="clear: both;"></div>
</div><!-- //header-wrap -->

<!-- content-wrap start -->
<div id="content-wrap"><div class="contents_s">

<!-- data_main -->
<div class="data_main">

<div class="data_attrs_pre">
作成日: 2007-03-14 22:47:19 &nbsp; / &nbsp; last updated at: 2008-12-24 22:51:26<br>
カテゴリ: <a href="category-21.html">Perl</a>&nbsp;</div>

<div class="data_body">
<ul class="plugin_navi">
<li>[&nbsp;<a href="./view-111.html" title="Perl/codepiece/static_vars1">Prev</a>&nbsp;]</li>
<li>[&nbsp;<a href="./view-117.html" title="Perl/codepiece/try-catch-exception02">Next</a>&nbsp;]</li>
<li>[&nbsp;<a href="./view-109.html" title="Perl">Perl</a>&nbsp;]</li>
</ul>
<hr class="full_hr" />

<p class="paragraph">
Perl(正確にはPerl5.X系列まで)にはtry-catch構文は存在しない。しかし、evalやcoderefを引数にとることができるなどの特徴を用い、幾つかの疑似try-catch的テクニックは存在する。Error.pmとうモジュールも公開されており、こちらを活用するとOOP的なtry-catchを実現できる。
<br />
</p>

<p class="paragraph">
参考ページ：
<br />
</p>
<ul><li> Error.pm<ul><li> <a class="externallink" href="http://search.cpan.org/~shlomif/Error-0.17008/lib/Error.pm" target="_blank">http://search.cpan.org/~shlomif/Error-0.17008/lib/Error.pm</a></li>
<li> <a class="externallink" href="http://www.perl.com/pub/a/2002/11/14/exception.html" target="_blank">http://www.perl.com/pub/a/2002/11/14/exception.html</a></li>
<li> <a class="externallink" href="http://www.perl.com/pub/a/2002/11/14/exception.html?page=2" target="_blank">http://www.perl.com/pub/a/2002/11/14/exception.html?page=2</a></li></ul></li>
<li> 日本語のError.pm紹介ブログentry<ul><li> <a class="externallink" href="http://qootas.org/blog/archives/2006/08/perltry_catch.html" target="_blank">http://qootas.org/blog/archives/2006/08/perltry_catch.html</a></li></ul></li></ul>

<h3 id="idad48b4">eval{}中のdieを$@で判別する基本形</h3>

<p class="paragraph">
eval{}コードブロック中でのdieは、コードを抜けた後、<strong> $@ </strong>変数で参照できる。これを利用して、以下のような疑似try-catch機能を利用できる。
<br />
</p>
<pre>eval {
    # do-something
    if ( exception-condition ) {
        die &quot;exception message&quot;;
    }
};
if ($@) {
    &amp;someErrorHandler($@);
}
</pre>

<p class="paragraph">
これが、perl.comにも載っているし、自分自身、恐らくどこかしかで目にしたのだろう、いつの間にかおぼえていた疑似コードである。(ひょっとしたらperl.comで目にした記憶が時間軸を前後したのかも知れない。)
<br />
</p>

<p class="paragraph">
これについてはわざわざコードピースを示すまでもない。
<br />
</p>

<h3 id="id793fd0">Error.pmの使用例</h3>

<p class="paragraph">
perl.comでも掲載されている、Perlでtry-catch, そしてOOPな例外処理機構を使用するのにお奨めのモジュール、それがError.pmらしい。perl.comに掲載されている記事やCPANのPODを元に、簡単なコードピースで実験をしてみる。
<br />
</p>

<ul><li> コードピース：スクリプトの引数に応じて発生させるErrorオブジェクトを変化させ、独自Errorや基本的なErrorを発生させてみる。</li></ul>
<pre>#!/usr/bin/perl

use strict;
use warnings;
use Data::Dumper;
use Error qw(:try);
use Switch;

my $d = shift || 0;
my $a = -1;

try {
	switch($d) {
		case -2 {
			# Error::Simpleをそのままthrowしてみる。
			throw Error::Simple(&quot;d = -2&quot;);
		}
		case -1 {
			# 元になるErrorオブジェクトを直にthrowしてみる。
			throw Error(-text =&gt; &quot;d = -1&quot;);
		}
		case 0 {
			# Error::Simpleをシンプルに継承したものをthrowしてみる。
			throw Error::TestException(&quot;d = 0&quot;);
		}
		# 以下はErrorを元にした独自Error
		case 1 {
			throw Test1HogeException(&quot;d = 1&quot;);
			}
		case 2 {
			throw Test2HogeException(&quot;d = 2&quot;);
			}
		else {
			throw HogeException(&quot;d = else&quot;);
		}
	}
	$a = $d;
} catch HogeException with {
	my $e = shift;
	print &quot;======== Hoge Exception ========\n&quot;;
	print Dumper($e), &quot;\n&quot;;
} catch Error with {
	my $e = shift;
	print &quot;e = $e\n&quot;;
	print Dumper($e), &quot;\n&quot;;
	print &quot;========warn======\n&quot;;
	warn $e-&gt;text;
} finally {
	print &quot;\n======= last a = [$a]\n&quot;;
};

package BoheException;
use base qw(Error);

package HogeException;
use base qw(Error);
use overload (&#039;&quot;&quot;&#039; =&gt; &#039;stringify&#039;);

sub new {
	my $self = shift;
	my $text = &quot;&quot;.shift;
	my @args = ();
	local $Error::Depth = $Error::Depth + 1;
	local $Error::Debug = 1;
	$self-&gt;SUPER::new(-text =&gt; $text, @args);
}

package Test1HogeException;
use base qw(HogeException);

package Test2HogeException;
use base qw(HogeException);

package Error::TestException;
use base qw(Error::Simple);
</pre>

<p class="paragraph">
引数に応じて何パターンか試してみる。
<br />
</p>
<ul><li> 引数 = -2</li></ul>
<pre>e = d = -2 at ./try03.pl line 15.

$VAR1 = bless( {
                 &#039;-file&#039; =&gt; &#039;./try03.pl&#039;,
                 &#039;-text&#039; =&gt; &#039;d = -2&#039;,
                 &#039;-line&#039; =&gt; 15,
                 &#039;-package&#039; =&gt; &#039;main&#039;
               }, &#039;Error::Simple&#039; );

========warn======
d = -2 at ./try03.pl line 43.

======= last a = [-1]
</pre>

<ul><li> 引数 = -1</li></ul>
<pre>e = d = -1
$VAR1 = bless( {
                 &#039;-file&#039; =&gt; &#039;./try03.pl&#039;,
                 &#039;-text&#039; =&gt; &#039;d = -1&#039;,
                 &#039;-line&#039; =&gt; 18,
                 &#039;-package&#039; =&gt; &#039;main&#039;
               }, &#039;Error&#039; );

========warn======
d = -1 at ./try03.pl line 43.

======= last a = [-1]
</pre>

<ul><li> 引数 = 0</li></ul>
<pre>e = d = 0 at ./try03.pl line 21.

$VAR1 = bless( {
                 &#039;-file&#039; =&gt; &#039;./try03.pl&#039;,
                 &#039;-text&#039; =&gt; &#039;d = 0&#039;,
                 &#039;-line&#039; =&gt; 21,
                 &#039;-package&#039; =&gt; &#039;main&#039;
               }, &#039;Error::TestException&#039; );

========warn======
d = 0 at ./try03.pl line 43.

======= last a = [-1]
</pre>

<ul><li> 引数 = 1</li></ul>
<pre>======== Hoge Exception ========
$VAR1 = bless( {
                 &#039;-stacktrace&#039; =&gt; &#039;d = 1 at ./try03.pl line 24
&#039;,
                 &#039;-file&#039; =&gt; &#039;./try03.pl&#039;,
                 &#039;-text&#039; =&gt; &#039;d = 1&#039;,
                 &#039;-line&#039; =&gt; 24,
                 &#039;-package&#039; =&gt; &#039;main&#039;
               }, &#039;Test1HogeException&#039; );


======= last a = [-1]
</pre>

<ul><li> 引数 = 2</li></ul>
<pre>======== Hoge Exception ========
$VAR1 = bless( {
                 &#039;-stacktrace&#039; =&gt; &#039;d = 2 at ./try03.pl line 27
&#039;,
                 &#039;-file&#039; =&gt; &#039;./try03.pl&#039;,
                 &#039;-text&#039; =&gt; &#039;d = 2&#039;,
                 &#039;-line&#039; =&gt; 27,
                 &#039;-package&#039; =&gt; &#039;main&#039;
               }, &#039;Test2HogeException&#039; );


======= last a = [-1]
</pre>

<ul><li> 引数 = 3</li></ul>
<pre>======== Hoge Exception ========
$VAR1 = bless( {
                 &#039;-stacktrace&#039; =&gt; &#039;d = else at ./try03.pl line 30
&#039;,
                 &#039;-file&#039; =&gt; &#039;./try03.pl&#039;,
                 &#039;-text&#039; =&gt; &#039;d = else&#039;,
                 &#039;-line&#039; =&gt; 30,
                 &#039;-package&#039; =&gt; &#039;main&#039;
               }, &#039;HogeException&#039; );


======= last a = [-1]
</pre>

<p class="paragraph">
細かい解説は見れば自明なので省略するが、とりあえず独自のErrorクラスを構築し、Javaなどと同じ使い心地で使用できるのを確認できた。
<br />
</p>

<h3 id="id95e79f">try{}中で直接 warn, die を使ってみる。</h3>

<p class="paragraph">
上記例はあくまでも教科書通りに、Errorオブジェクトをthrowしている。では実際に、try {} 中で die や warn が発生するとどうなるかを確認しておく。
<br />
</p>

<ul><li> コードピース</li></ul>
<pre>#!/usr/bin/perl
use strict;
use warnings;
use Data::Dumper;
use Error qw(:try);

try {
    warn &quot;warning!!&quot;;
    die &quot;die!!&quot;;
} catch Error with {
    my $e = shift;
    print &quot;e = $e\n&quot;;
    print Dumper($e), &quot;\n&quot;;
    print &quot;========warn======\n&quot;;
    warn $e-&gt;text;
} finally {
    print &quot;\n======= last \n&quot;;
};
</pre>

<ul><li> 出力</li></ul>
<pre>warning!! at ./try04.pl line 9.
e = die!! at ./try04.pl line 10.

$VAR1 = bless( {
                 &#039;-file&#039; =&gt; &#039;./try04.pl&#039;,
                 &#039;-text&#039; =&gt; &#039;die!!&#039;,
                 &#039;-line&#039; =&gt; &#039;10&#039;,
                 &#039;-package&#039; =&gt; &#039;Error&#039;
               }, &#039;Error::Simple&#039; );

========warn======
die!! at ./try04.pl line 16.

======= last
</pre>

<p class="paragraph">
<strong> die の場合、Error::Simpleにラッピングされてthrowされていることを確認できた。 </strong>
<br />
</p>

<h3 id="idb746a4">try{}中で直接 carp, croak を使ってみる。</h3>

<p class="paragraph">
warn, die と同じ効果になると思われる。
<br />
</p>

<ul><li> コードピース</li></ul>
<pre>#!/usr/bin/perl
use strict;
use warnings;
use Data::Dumper;
use Carp;
use Error qw(:try);

try {
    carp &quot;carp!!&quot;;
    croak &quot;croak!!&quot;;
} catch Error with {
    my $e = shift;
    print &quot;e = $e\n&quot;;
    print Dumper($e), &quot;\n&quot;;
    print &quot;========warn======\n&quot;;
    warn $e-&gt;text;
} finally {
    print &quot;\n======= last \n&quot;;
};
</pre>

<ul><li> 出力</li></ul>
<pre>carp!! at /usr/lib/perl5/site_perl/5.8.5/Error.pm line 428
e = croak!! at /usr/lib/perl5/site_perl/5.8.5/Error.pm line 428.

$VAR1 = bless( {
                 &#039;-file&#039; =&gt; &#039;/usr/lib/perl5/site_perl/5.8.5/Error.pm&#039;,
                 &#039;-text&#039; =&gt; &#039;croak!!&#039;,
                 &#039;-line&#039; =&gt; &#039;428&#039;,
                 &#039;-package&#039; =&gt; &#039;Error&#039;
               }, &#039;Error::Simple&#039; );

========warn======
croak!! at ./try04.pl line 19.

======= last
</pre>

<p class="paragraph">
ほぼ予想通りである。<a href="./view-115.html" >Perl/codepiece/carp01</a>では、(carp,croak)と(cluck,confess)系で違いが見られなかった、とあるが、ここでようやく明らかな出力の差異が認められた。上記コードピースのcarp, croakをそれぞれcluck, confessで置き換えた結果を下に示す。
<br />
</p>

<pre>cluck!! at ./try04.pl line 12
        main::__ANON__() called at /usr/lib/perl5/site_perl/5.8.5/Error.pm line 428
        eval {...} called at /usr/lib/perl5/site_perl/5.8.5/Error.pm line 420
        Error::subs::try(&#039;CODE(0x816446c)&#039;, &#039;HASH(0x8164448)&#039;) called at ./try04.pl line 24
e = confess!! at ./try04.pl line 15
        main::__ANON__() called at /usr/lib/perl5/site_perl/5.8.5/Error.pm line 428
        eval {...} called at /usr/lib/perl5/site_perl/5.8.5/Error.pm line 420
        Error::subs::try(&#039;CODE(0x816446c)&#039;, &#039;HASH(0x8164448)&#039;) called at ./try04.pl line 24.

$VAR1 = bless( {
                 &#039;-file&#039; =&gt; &#039;./try04.pl&#039;,
                 &#039;-text&#039; =&gt; &#039;confess!! at ./try04.pl line 15
        main::__ANON__() called at /usr/lib/perl5/site_perl/5.8.5/Error.pm line 428
        eval {...} called at /usr/lib/perl5/site_perl/5.8.5/Error.pm line 420
        Error::subs::try(\&#039;CODE(0x816446c)\&#039;, \&#039;HASH(0x8164448)\&#039;) called&#039;,
                 &#039;-line&#039; =&gt; &#039;24&#039;,
                 &#039;-package&#039; =&gt; &#039;Error&#039;
               }, &#039;Error::Simple&#039; );

========warn======
confess!! at ./try04.pl line 15
        main::__ANON__() called at /usr/lib/perl5/site_perl/5.8.5/Error.pm line 428
        eval {...} called at /usr/lib/perl5/site_perl/5.8.5/Error.pm line 420
        Error::subs::try(&#039;CODE(0x816446c)&#039;, &#039;HASH(0x8164448)&#039;) called at ./try04.pl line 21.

======= last
</pre>

<p class="paragraph">
このように、cluck, confessを使用すると、細かいスタックトレースが出力できることが分かった。
<br />
</p>

<p class="paragraph">
結論として<strong> Error.pm と Carp 系は共存可能 </strong>であることを確認できた。
<br />
</p>

<hr class="full_hr" />
<ul class="plugin_navi">
<li>[&nbsp;<a href="./view-111.html" title="Perl/codepiece/static_vars1">Prev</a>&nbsp;]</li>
<li>[&nbsp;<a href="./view-117.html" title="Perl/codepiece/try-catch-exception02">Next</a>&nbsp;]</li>
<li>[&nbsp;<a href="./view-109.html" title="Perl">Perl</a>&nbsp;]</li>
</ul>
</div>

<div class="data_attrs_post">
original url: https://www.glamenv-septzen.net/view/116<br>
</div>

</div>
<!-- //data_main -->

</div>


</div>
<!-- /content-wrap end -->

<!-- footer start -->
<div id="footer">
Copyright &copy; 2001 - 2025 Masahiko Sakamoto(msakamoto-sf)<br>
License&nbsp;:&nbsp;<a target="_blank" href="http://www.apache.org/licenses/LICENSE-2.0">Apache License, Version 2.0</a><br>
Contact&nbsp;:&nbsp;<a target="_blank" href="https://x.com/msakamoto_sf">x(twitter)</a> / <a target="_blank" href="https://github.com/msakamoto-sf/">github</a> / <a class="maillink" target="_blank" href="mailto:&#x73;&#x61;&#x6B;&#x61;&#x6D;&#x6F;&#x74;&#x6F;&#x2E;&#x67;&#x73;&#x79;&#x63;&#x2E;&#x33;&#x73;&#x40;&#x67;&#x6D;&#x61;&#x69;&#x6C;&#x2E;&#x63;&#x6F;&#x6D;">email</a><br>
--&nbsp;Beautiful Icons&nbsp;--<br />
<a href="http://www.famfamfam.com/lab/icons/silk/" target="_blank" title="Mark James Silk icon set 1.3">Mark James Silk icon set 1.3</a> by famfamfam<br />
<a href="http://www.pinvoke.com/" target="_blank" title="Fugue Icons">Fugue Icons</a> by Yusuke Kamiyamane<br />
</div>
<!-- /footer end -->

</div>
<!-- /body end -->

</body>
</html>